### PR TITLE
Added cata spec detection

### PR DESCRIPTION
**Pull request by Spongie**
Healers are sorted to the end in GUI
Added option to not show spec

### CODE REVIEW

**Comment by denishamann** [comment]
Hello Philip,

Thank you for your PR and apologies for my delayed response. I'll go ahead and approve it as is since I no longer play the game. If you're willing to also review the viewer repository and make any necessary adaptations, that would be greatly appreciated.

**Comment by denishamann** [comment]
Here is the link to the visualizer:

https://github.com/denishamann/arena-stats-visualizer

**Comment by Spongie** [comment]
Will you update the addon on Curseforge as well?
The visualizer still works even with the new data, but I am working on updates to include this new data and more statistics as well

**Comment by denishamann** [comment]
@Spongie Gentle ping to let you know I pushed the 0.2.4 version to Curseforge, thanks again for your work.

**Pull request merged**
